"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps, react-hooks/static-components */

import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowDown, ArrowUp, Bike, CalendarDays, CircleStop, Map, Navigation, Pause, Play, RefreshCw, RotateCcw, Route, Save, Search, Trash2, UploadCloud } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type Point = { lat: number; lng: number; time?: number; speed?: number; ele?: number };
type Course = { id: string; name: string; start: Point; end: Point; waypoints?:Point[]; preference?:"bike"|"shared"|"road"; createdAt: number };
type Ride = { id: string; courseName: string; startedAt: number; endedAt: number; distance: number; maxSpeed: number; elevation?:number; uploaded?:boolean; uploadId?:number; stravaActivityId?:number; points: Point[] };
type StravaActivity={id:number;name:string;start_date_local:string;distance:number;moving_time:number;average_speed:number;total_elevation_gain:number;external_id?:string;map?:{summary_polyline?:string};sport_type?:string};
type KMap = { setCenter:(p:unknown)=>void; setBounds:(b:unknown)=>void; addControl:(c:unknown,p:unknown)=>void; relayout:()=>void };
type Overlay = { setMap:(map:unknown|null)=>void };
type Polyline = Overlay & { setPath:(path:unknown[])=>void };

declare global { interface Window { kakao?: { maps: {
  load:(cb:()=>void)=>void; Map:new(el:HTMLElement,o:{center:unknown;level:number})=>KMap;
  LatLng:new(lat:number,lng:number)=>{getLat:()=>number;getLng:()=>number};
  LatLngBounds:new()=>{extend:(p:unknown)=>void};
  Marker:new(o:{position:unknown})=>Overlay; Polyline:new(o:{path:unknown[];strokeWeight:number;strokeColor:string;strokeOpacity:number})=>Polyline;
  ZoomControl:new()=>unknown; ControlPosition:{RIGHT:unknown};
  event:{addListener:(target:unknown,event:string,cb:(e:{latLng:{getLat:()=>number;getLng:()=>number}})=>void)=>void};
  services:{Places:new()=>{keywordSearch:(q:string,cb:(data:Array<{id:string;place_name:string;address_name:string;road_address_name:string;x:string;y:string}>,status:string)=>void)=>void};Status:{OK:string}}
} } } }

const SEOUL = { lat:37.5665, lng:126.978 }, COURSE_KEY="riding-saved-courses", RIDE_KEY="riding-saved-rides";
type Weather={temperature:number;apparent:number;wind:number;gust:number;rainChance:number;sunset:string;score:number;summary:string;temperatureNote:string;windNote:string;rainNote:string};
const distance=(a:Point,b:Point)=>{const r=6371000,rad=(v:number)=>v*Math.PI/180,dLat=rad(b.lat-a.lat),dLng=rad(b.lng-a.lng),x=Math.sin(dLat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dLng/2)**2;return 2*r*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const pathDistance=(p:Point[])=>p.slice(1).reduce((s,x,i)=>s+distance(p[i],x),0);
const fmtDistance=(m:number)=>m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(2)} km`;
const fmtTime=(ms:number)=>{const t=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(t/3600)).padStart(2,"0")}:${String(Math.floor(t%3600/60)).padStart(2,"0")}:${String(t%60).padStart(2,"0")}`};

export default function Home(){
 const todayEl=useRef<HTMLDivElement>(null),courseEl=useRef<HTMLDivElement>(null),rideEl=useRef<HTMLDivElement>(null),recordEl=useRef<HTMLDivElement>(null);
 const maps=useRef<Record<string,KMap>>({}), overlays=useRef<Record<string,Overlay[]>>({}), watchId=useRef<number|null>(null), started=useRef(0),pauseStarted=useRef(0),pausedTotal=useRef(0),pausedRef=useRef(false),wakeLock=useRef<{release:()=>Promise<void>}|null>(null);
 const [tab,setTab]=useState("today"),[key,setKey]=useState(""),[draftKey,setDraftKey]=useState(""),[status,setStatus]=useState<"setup"|"loading"|"ready"|"error">("setup"),[message,setMessage]=useState("카카오 JavaScript 키를 입력하면 지도가 열립니다.");
 const [weather,setWeather]=useState<Weather|null>(null),[weatherMessage,setWeatherMessage]=useState("위치를 확인하면 실제 날씨를 불러옵니다.");
 const [courses,setCourses]=useState<Course[]>([]),[rides,setRides]=useState<Ride[]>([]),[courseName,setCourseName]=useState(""),[start,setStart]=useState<Point|null>(null),[end,setEnd]=useState<Point|null>(null);
 const [waypoints,setWaypoints]=useState<Point[]>([]),[pickMode,setPickMode]=useState<"start"|"waypoint"|"end">("start"),[preference,setPreference]=useState<"bike"|"shared"|"road">("bike");
 const [search,setSearch]=useState(""),[results,setResults]=useState<Array<{id:string;name:string;address:string;point:Point}>>([]),[courseId,setCourseId]=useState(""),[ridePoints,setRidePoints]=useState<Point[]>([]),[riding,setRiding]=useState(false),[freeRiding,setFreeRiding]=useState(false),[paused,setPaused]=useState(false),[elapsed,setElapsed]=useState(0),[gpsAccuracy,setGpsAccuracy]=useState<number|null>(null),[gpsSkipped,setGpsSkipped]=useState(0),[notice,setNotice]=useState("코스 주행 또는 현재 위치 자유 주행을 시작하세요."),[rideId,setRideId]=useState("");
 const [strava,setStrava]=useState<StravaActivity[]>([]),[stravaConnected,setStravaConnected]=useState(false),[syncing,setSyncing]=useState(false),[recordMessage,setRecordMessage]=useState(""),[calendarDate,setCalendarDate]=useState(new Date());
 const [yearlyStrava,setYearlyStrava]=useState<StravaActivity[]>([]),[lastSynced,setLastSynced]=useState(""),[yearComplete,setYearComplete]=useState(true);
 const [showGuide,setShowGuide]=useState(false);
 const selectedCourse=courses.find(c=>c.id===courseId)||null,rideDistance=useMemo(()=>pathDistance(ridePoints),[ridePoints]),avgSpeed=elapsed?rideDistance/(elapsed/1000)*3.6:0;

 useEffect(()=>{const k=localStorage.getItem("riding-kakao-js-key")||"";if(k){setKey(k);setDraftKey(k)}setShowGuide(!localStorage.getItem("riding-guide-complete"));try{setCourses(JSON.parse(localStorage.getItem(COURSE_KEY)||"[]"));setRides(JSON.parse(localStorage.getItem(RIDE_KEY)||"[]"));setStrava(JSON.parse(localStorage.getItem("riding-strava-activities")||"[]"))}catch{}void syncStrava(false)},[]);
 useEffect(()=>{if(!key)return;setStatus("loading");document.querySelector("script[data-kakao-map]")?.remove();delete window.kakao;const s=document.createElement("script");s.dataset.kakaoMap="true";s.async=true;s.src=`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${encodeURIComponent(key)}&autoload=false&libraries=services`;s.onload=()=>window.kakao?.maps.load(()=>{setStatus("ready");setMessage("지도가 연결되었습니다.");setTimeout(initMaps,0);locate()});s.onerror=()=>{setStatus("error");setMessage("지도를 열지 못했습니다. 키와 등록 주소를 확인해 주세요.")};document.head.appendChild(s);return()=>s.remove()},[key]);
 useEffect(()=>{if(status==="ready")setTimeout(()=>{initMaps();maps.current[tab]?.relayout();redraw()},30)},[tab,status]);
 useEffect(()=>{if(!riding||paused)return;const t=setInterval(()=>setElapsed(Date.now()-started.current-pausedTotal.current),1000);return()=>clearInterval(t)},[riding,paused]);

 function makeMap(name:string,el:HTMLDivElement|null,level=6){if(!window.kakao||!el||maps.current[name])return;const m=new window.kakao.maps.Map(el,{center:new window.kakao.maps.LatLng(SEOUL.lat,SEOUL.lng),level});m.addControl(new window.kakao.maps.ZoomControl(),window.kakao.maps.ControlPosition.RIGHT);maps.current[name]=m;overlays.current[name]=[];if(name==="course")window.kakao.maps.event.addListener(m,"click",e=>pickPoint({lat:e.latLng.getLat(),lng:e.latLng.getLng()}))}
 function initMaps(){makeMap("today",todayEl.current);makeMap("course",courseEl.current);makeMap("ride",rideEl.current,5);makeMap("records",recordEl.current,5);redraw()}
 function clear(name:string){overlays.current[name]?.forEach(o=>o.setMap(null));overlays.current[name]=[]}
 function addMarker(name:string,p:Point){if(!window.kakao||!maps.current[name])return;const m=new window.kakao.maps.Marker({position:new window.kakao.maps.LatLng(p.lat,p.lng)});m.setMap(maps.current[name]);overlays.current[name].push(m)}
 function addLine(name:string,p:Point[],color="#176b4a"){if(!window.kakao||!maps.current[name]||p.length<2)return;const l=new window.kakao.maps.Polyline({path:p.map(x=>new window.kakao!.maps.LatLng(x.lat,x.lng)),strokeWeight:6,strokeColor:color,strokeOpacity:.85});l.setMap(maps.current[name]);overlays.current[name].push(l)}
 function redraw(){if(!window.kakao)return;clear("course");if(start)addMarker("course",start);waypoints.forEach(p=>addMarker("course",p));if(end)addMarker("course",end);if(start&&end)addLine("course",[start,...waypoints,end]);clear("ride");if(selectedCourse&&!freeRiding){addMarker("ride",selectedCourse.start);addMarker("ride",selectedCourse.end);addLine("ride",[selectedCourse.start,...(selectedCourse.waypoints||[]),selectedCourse.end],"#9ab43b")}if(ridePoints.length){addLine("ride",ridePoints);addMarker("ride",ridePoints.at(-1)!)}const r=rides.find(x=>x.id===rideId);clear("records");if(r?.points.length){addLine("records",r.points);addMarker("records",r.points[0]);addMarker("records",r.points.at(-1)!);maps.current.records?.setCenter(new window.kakao.maps.LatLng(r.points[0].lat,r.points[0].lng))}}
 useEffect(redraw,[start,end,waypoints,courseId,ridePoints,rideId,rides,freeRiding]);

 function locate(){if(!navigator.geolocation){void loadWeather(SEOUL.lat,SEOUL.lng,"서울시청 기준");return}setMessage("현재 위치를 찾는 중입니다…");navigator.geolocation.getCurrentPosition(({coords})=>{const p={lat:coords.latitude,lng:coords.longitude};if(!window.kakao)return;Object.values(maps.current).forEach(m=>m.setCenter(new window.kakao!.maps.LatLng(p.lat,p.lng)));clear("today");addMarker("today",p);setMessage("현재 위치를 지도에 표시했습니다.");void loadWeather(p.lat,p.lng,"현재 위치 기준")},()=>{setMessage("위치 권한이 없어 서울시청을 표시합니다.");void loadWeather(SEOUL.lat,SEOUL.lng,"서울시청 기준")},{enableHighAccuracy:true,timeout:10000,maximumAge:60000})}
 async function loadWeather(lat:number,lng:number,label:string){setWeatherMessage(`${label} 날씨를 불러오는 중입니다…`);try{const q=new URLSearchParams({latitude:String(lat),longitude:String(lng),timezone:"auto",wind_speed_unit:"ms",current:"temperature_2m,apparent_temperature,precipitation,rain,weather_code,wind_speed_10m,wind_gusts_10m",daily:"sunrise,sunset,precipitation_probability_max"}),d=await(await fetch(`https://api.open-meteo.com/v1/forecast?${q}`)).json(),c=d.current,a=Number(c.apparent_temperature),w=Number(c.wind_speed_10m),g=Number(c.wind_gusts_10m),rain=Number(c.rain||0),chance=Number(d.daily.precipitation_probability_max[0]||0),sunset=d.daily.sunset[0],sunrise=d.daily.sunrise[0];let score=100;if(a<=0)score-=30;else if(a<5)score-=20;else if(a>=35)score-=40;else if(a>=30)score-=25;if(w>=15)score-=40;else if(w>=10)score-=28;else if(w>=7)score-=18;if(g>=14)score-=10;if(rain>0)score-=35;if(chance>=70)score-=25;else if(chance>=40)score-=15;const now=new Date();if(now<new Date(sunrise)||now>new Date(sunset))score-=20;score=Math.max(0,Math.min(100,Math.round(score)));setWeather({temperature:Number(c.temperature_2m),apparent:a,wind:w,gust:g,rainChance:chance,sunset,score,summary:score>=85?"라이딩하기 아주 좋은 날이에요":score>=70?"가볍게 달리기 좋은 날이에요":score>=50?"주의하며 짧게 달리세요":"오늘은 라이딩을 미루세요",temperatureNote:a>=30?"더위 주의":a<=5?"방한 준비":"쾌적해요",windNote:w>=10?"강풍 주의":w>=7?"바람 주의":"약한 바람",rainNote:rain>0?"현재 비가 와요":chance>=40?"우비를 챙기세요":"비 가능성 낮음"});setWeatherMessage(`${label} · ${new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})} 갱신`)}catch{setWeatherMessage("날씨를 불러오지 못했습니다. 현재 위치를 다시 눌러주세요.")}}
 function saveKey(){const k=draftKey.trim();if(!k)return setMessage("JavaScript 키를 입력해 주세요.");localStorage.setItem("riding-kakao-js-key",k);setKey(k)}
 function pickPoint(p:Point){if(pickMode==="start"){setStart(p);setEnd(null);setWaypoints([]);setPickMode("end");setMessage("출발점을 정했습니다. 도착점을 선택하거나 경유지를 추가하세요.")}else if(pickMode==="waypoint"){if(waypoints.length>=5)return setMessage("경유지는 최대 5개까지 설정할 수 있습니다.");setWaypoints(v=>[...v,p]);setPickMode("end");setMessage(`경유지 ${waypoints.length+1}을 추가했습니다.`)}else{setEnd(p);setMessage("도착점을 정했습니다. 코스 이름을 입력해 저장하세요.")}}
 function searchPlaces(){if(!window.kakao||!search.trim())return;new window.kakao.maps.services.Places().keywordSearch(search.trim(),(d,s)=>setResults(s===window.kakao!.maps.services.Status.OK?d.slice(0,6).map(x=>({id:x.id,name:x.place_name,address:x.road_address_name||x.address_name,point:{lat:Number(x.y),lng:Number(x.x)}})):[]))}
 function saveCourse(){if(!start||!end)return setMessage("지도에서 출발점과 도착점을 선택해 주세요.");const c={id:crypto.randomUUID(),name:courseName.trim()||`나의 코스 ${courses.length+1}`,start,end,waypoints,preference,createdAt:Date.now()},all=[c,...courses];setCourses(all);localStorage.setItem(COURSE_KEY,JSON.stringify(all));setCourseId(c.id);setCourseName("");setMessage("코스와 경유지·경로 우선순위를 저장했습니다.")}
 function undoCoursePoint(){if(end){setEnd(null);setPickMode("end");setMessage("도착점을 취소했습니다.")}else if(waypoints.length){setWaypoints(v=>v.slice(0,-1));setPickMode("waypoint");setMessage("마지막 경유지를 취소했습니다.")}else if(start){setStart(null);setPickMode("start");setMessage("출발점을 취소했습니다.")}}
 function resetCourse(){setStart(null);setEnd(null);setWaypoints([]);setPickMode("start");setMessage("코스 지점을 모두 초기화했습니다.")}
 function moveWaypoint(index:number,direction:-1|1){setWaypoints(v=>{const next=[...v],target=index+direction;if(target<0||target>=next.length)return v;[next[index],next[target]]=[next[target],next[index]];return next})}
 function deleteCourse(id:string){const all=courses.filter(c=>c.id!==id);setCourses(all);localStorage.setItem(COURSE_KEY,JSON.stringify(all));if(courseId===id)setCourseId("")}
 function beginRide(free=false){if(!free&&!selectedCourse)return setNotice("저장한 코스를 선택하거나 자유 주행을 눌러 주세요.");if(!navigator.geolocation)return setNotice("이 기기에서는 위치 기능을 사용할 수 없습니다.");setFreeRiding(free);setRidePoints([]);setElapsed(0);setPaused(false);pausedRef.current=false;setGpsAccuracy(null);setGpsSkipped(0);pausedTotal.current=0;started.current=Date.now();setRiding(true);setNotice(free?"현재 위치에서 자유 주행을 기록합니다. 앱을 닫거나 강제 종료하지 마세요.":"코스 주행 GPS 기록 중입니다. 앱을 닫거나 강제 종료하지 마세요.");const nav=navigator as Navigator&{wakeLock?:{request:(type:"screen")=>Promise<{release:()=>Promise<void>}>}};void nav.wakeLock?.request("screen").then(lock=>{wakeLock.current=lock}).catch(()=>setNotice("GPS 기록 중입니다. 화면이 꺼지지 않도록 유지해 주세요."));watchId.current=navigator.geolocation.watchPosition(({coords,timestamp})=>{setGpsAccuracy(Math.round(coords.accuracy));if(pausedRef.current)return;const p={lat:coords.latitude,lng:coords.longitude,time:timestamp,speed:coords.speed==null?undefined:coords.speed*3.6,ele:coords.altitude??undefined};setRidePoints(old=>{if(coords.accuracy>60){setGpsSkipped(v=>v+1);return old}const previous=old.at(-1);if(previous){const seconds=Math.max(1,(timestamp-(previous.time||timestamp))/1000),calculatedSpeed=distance(previous,p)/seconds*3.6;if(calculatedSpeed>70){setGpsSkipped(v=>v+1);return old}}return[...old,p]});if(window.kakao)maps.current.ride?.setCenter(new window.kakao.maps.LatLng(p.lat,p.lng))},()=>setNotice("위치를 읽지 못했습니다. 브라우저 위치 권한을 확인해 주세요."),{enableHighAccuracy:true,maximumAge:1000,timeout:15000})}
 function togglePause(){if(!riding)return;if(paused){pausedTotal.current+=Date.now()-pauseStarted.current;pausedRef.current=false;setPaused(false);setNotice("GPS 기록을 계속합니다.")}else{pauseStarted.current=Date.now();pausedRef.current=true;setPaused(true);setNotice("주행 기록을 일시정지했습니다.")}}
 function stopRide(){if(!window.confirm("주행을 종료하고 기록을 저장할까요?"))return;if(watchId.current!==null)navigator.geolocation.clearWatch(watchId.current);watchId.current=null;void wakeLock.current?.release().catch(()=>undefined);wakeLock.current=null;setRiding(false);const activePause=pausedRef.current?Date.now()-pauseStarted.current:0;pausedRef.current=false;setPaused(false);const finishedAt=Date.now()-pausedTotal.current-activePause;if(ridePoints.length<2)return setNotice("기록된 위치가 너무 적어 저장하지 않았습니다.");const elevation=ridePoints.slice(1).reduce((s,p,i)=>s+(p.ele!=null&&ridePoints[i].ele!=null?Math.max(0,p.ele-ridePoints[i].ele!):0),0),r={id:crypto.randomUUID(),courseName:freeRiding?"자유 주행":selectedCourse?.name||"자유 주행",startedAt:started.current,endedAt:finishedAt,distance:pathDistance(ridePoints),maxSpeed:Math.max(0,...ridePoints.map(p=>p.speed||0)),elevation,points:ridePoints},all=[r,...rides].slice(0,100);setRides(all);localStorage.setItem(RIDE_KEY,JSON.stringify(all));setRideId(r.id);setNotice(`주행을 저장했습니다. 정확도가 낮은 GPS ${gpsSkipped}개는 거리에서 제외했습니다.`);setFreeRiding(false)}
 function deleteRide(id:string){const all=rides.filter(r=>r.id!==id);setRides(all);localStorage.setItem(RIDE_KEY,JSON.stringify(all));if(rideId===id)setRideId("")}
 async function syncStrava(show=true){setSyncing(true);try{const r=await fetch("/api/strava/activities"),d=await r.json();setStravaConnected(Boolean(d.connected));if(d.connected){const a=(d.activities||[]).slice(0,100),year=d.yearActivities||a,synced=d.syncedAt||new Date().toISOString();setStrava(a);setYearlyStrava(year);setLastSynced(synced);setYearComplete(d.complete!==false);localStorage.setItem("riding-strava-activities",JSON.stringify(a));if(show)setRecordMessage(d.complete===false?"Strava 기록이 많아 일부만 집계되었습니다. 잠시 후 다시 동기화해 주세요.":`올해 전체 ${year.length}개를 확인하고 최근 ${a.length}개를 저장했습니다.`)}}catch{if(show)setRecordMessage("Strava 기록을 가져오지 못했습니다.")}finally{setSyncing(false)}}
 async function uploadRide(ride:Ride){setRecordMessage("Strava에 업로드하고 완료 여부를 확인하는 중입니다…");const r=await fetch("/api/strava/upload",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(ride)}),d=await r.json();if(!r.ok)return setRecordMessage(d.error||"업로드하지 못했습니다.");let all=rides.map(x=>x.id===ride.id?{...x,uploadId:Number(d.uploadId)||undefined}:x);setRides(all);localStorage.setItem(RIDE_KEY,JSON.stringify(all));for(let attempt=0;attempt<6;attempt++){await new Promise(resolve=>setTimeout(resolve,2000));const check=await fetch(`/api/strava/upload/status?id=${encodeURIComponent(d.uploadId)}`),result=await check.json();if(result.error){setRecordMessage(result.error);return}if(result.complete){all=all.map(x=>x.id===ride.id?{...x,uploaded:true,stravaActivityId:Number(result.activityId)}:x);setRides(all);localStorage.setItem(RIDE_KEY,JSON.stringify(all));setRecordMessage("Strava 업로드가 완료되었습니다. 기록을 다시 동기화합니다.");await syncStrava(false);return}}setRecordMessage("Strava에서 처리 중입니다. 잠시 후 기록 동기화를 눌러 주세요.")}
 function closeGuide(){localStorage.setItem("riding-guide-complete","1");setShowGuide(false)}
 const MapSetup=()=>status==="setup"||status==="error"?<div className="setupPanel"><div className="kakaoBadge">KAKAO MAP</div><h3>{status==="error"?"지도를 열지 못했어요":"지도 연결하기"}</h3><p>카카오 Developers의 <b>JavaScript 키</b>를 붙여 넣으세요.</p><input type="password" value={draftKey} onChange={e=>setDraftKey(e.target.value)} placeholder="키를 여기에 붙여 넣기"/><button onClick={saveKey}>카카오 지도 열기</button><small>키와 기록은 이 기기에만 저장됩니다.</small></div>:status==="loading"?<div className="loadingPanel"><span className="spinner"/>지도 준비 중</div>:null;

 return <main><header className="topbar"><div className="brand"><span className="brandMark">↗</span><div><strong>내 라이딩 비서</strong><span>오늘의 라이딩을 더 안전하게</span></div></div><button className="guideButton" onClick={()=>setShowGuide(true)}>처음 사용 안내</button><div className="live"><span/>라이딩 준비</div></header><section className="dashboard">{showGuide&&<section className="beginnerGuide" aria-label="처음 사용 안내"><div><p className="eyebrow">처음 사용하시나요?</p><h2>세 가지만 준비하면 됩니다.</h2></div><ol><li><b>1</b><span><strong>위치 허용</strong><small>현재 위치와 주행 경로를 기록합니다.</small></span></li><li><b>2</b><span><strong>카카오 지도 연결</strong><small>JavaScript 키는 이 기기에만 저장됩니다.</small></span></li><li><b>3</b><span><strong>Strava 연결은 선택</strong><small>기록을 가져오거나 업로드할 때만 필요합니다.</small></span></li></ol><button onClick={closeGuide}>알겠습니다 · 시작하기</button></section>}<Tabs value={tab} onValueChange={setTab} className="appTabs"><TabsList className="tabBar"><TabsTrigger value="today"><CalendarDays/>오늘</TabsTrigger><TabsTrigger value="course"><Route/>코스</TabsTrigger><TabsTrigger value="ride"><Navigation/>주행</TabsTrigger><TabsTrigger value="records"><Map/>기록</TabsTrigger></TabsList>
 <TabsContent value="today"><div className="intro"><div><p className="eyebrow">RIDE SMART · RIDE SAFE</p><h1>출발 전에<br/><em>길부터 확인하세요.</em></h1><p className="introText">현재 위치의 날씨와 실제 카카오 지도를 확인하고 안전하게 라이딩을 준비하세요.</p></div><div className="scoreCard"><span>현재 라이딩 지수</span><strong>{weather?.score??"--"}<small>점</small></strong><p>{weather?.summary??"위치를 확인하고 있어요"}</p><small className="weatherSource">{weatherMessage}</small></div></div><div className="quickActions"><button onClick={()=>setTab("course")}><Route/><span><strong>코스 만들기</strong><small>출발·경유·도착 설정</small></span></button><button onClick={()=>setTab("ride")}><Navigation/><span><strong>주행 시작</strong><small>저장한 코스로 GPS 기록</small></span></button><button onClick={()=>setTab("records")}><Map/><span><strong>최근 기록</strong><small>달력과 누적거리 확인</small></span></button></div><div className="stats"><Stat label="기온 · 체감" value={weather?`${Math.round(weather.temperature)}° · ${Math.round(weather.apparent)}°`:"--"} note={weather?.temperatureNote||"불러오는 중"}/><Stat label="바람 · 돌풍" value={weather?`${weather.wind.toFixed(1)} m/s`:"--"} note={weather?`${weather.windNote} · 돌풍 ${weather.gust.toFixed(1)}`:"불러오는 중"}/><Stat label="오늘 강수확률" value={weather?`${weather.rainChance}%`:"--"} note={weather?.rainNote||"불러오는 중"}/><Stat label="일몰" value={weather?new Date(weather.sunset).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false}):"--"} note="야간 라이트 확인"/></div><MapCard title="내 주변 라이딩 지도" message={message} mapRef={todayEl} setup={<MapSetup/>} action={<button className="primaryButton" onClick={locate} disabled={status!=="ready"}>◎ 현재 위치</button>}/></TabsContent>
 <TabsContent value="course"><PageTitle eyebrow="COURSE MAKER" title="라이딩 코스 찾기·저장" text="출발지·도착지와 최대 5개의 경유지를 순서대로 지정하세요."/>
  <div className="courseSteps" aria-label="코스 만들기 진행 단계"><span className={start?"done":"active"}>1 출발지</span><span className={start&&!end?"active":end?"done":""}>2 경유지·도착지</span><span className={start&&end?"active":""}>3 이름·저장</span><span>4 주행 시작</span></div>
  <div className="split"><aside className="sidePanel"><p className="currentStep">{!start?"① 출발지를 검색하거나 지도에서 선택하세요.":!end?`② ${waypoints.length?`경유지 ${waypoints.length}개 설정됨 · `:""}경유지를 더하거나 도착지를 선택하세요.`:"③ 코스 이름을 확인하고 저장하세요."}</p><div className="searchBox"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchPlaces()} placeholder="장소 검색 (예: 반포한강공원)"/><button onClick={searchPlaces} aria-label="장소 검색"><Search/></button></div>
  {results.length>0&&<div className="searchResults">{results.map(r=><button key={r.id} onClick={()=>{pickPoint(r.point);maps.current.course?.setCenter(new window.kakao!.maps.LatLng(r.point.lat,r.point.lng))}}><strong>{r.name}</strong><span>{r.address}</span></button>)}</div>}
  <div className="formBlock"><label>지점 선택</label><div className="modeButtons"><button className={pickMode==="start"?"active":""} onClick={()=>setPickMode("start")}>출발지</button><button className={pickMode==="waypoint"?"active":""} onClick={()=>setPickMode("waypoint")} disabled={waypoints.length>=5}>경유지 추가</button><button className={pickMode==="end"?"active":""} onClick={()=>setPickMode("end")}>도착지</button></div><div className="pointStatus"><span className={start?"done":""}>출발 {start?"완료":"미설정"}</span><span className={end?"done":""}>도착 {end?"완료":"미설정"}</span></div>
  <div className="waypointList">{waypoints.map((_,i)=><div key={i}><span><b>{i+1}</b> 경유지 {i+1}</span><span className="waypointActions"><button onClick={()=>moveWaypoint(i,-1)} disabled={i===0} aria-label={`경유지 ${i+1} 위로 이동`}><ArrowUp/></button><button onClick={()=>moveWaypoint(i,1)} disabled={i===waypoints.length-1} aria-label={`경유지 ${i+1} 아래로 이동`}><ArrowDown/></button><button onClick={()=>setWaypoints(v=>v.filter((_,n)=>n!==i))}>삭제</button></span></div>)}{waypoints.length===0&&<small>경유지는 필요한 경우에만 최대 5개까지 추가하세요.</small>}</div>
  <label>경로 탐색 우선순위</label><select className="routePreference" value={preference} onChange={e=>setPreference(e.target.value as "bike"|"shared"|"road")}><option value="bike">1. 자전거 전용도로 우선</option><option value="shared">2. 자전거·보행 공용도로 우선</option><option value="road">3. 일반도로 우선</option></select><p className="routeNote"><b>안내:</b> 현재 지도 선은 선택한 지점을 순서대로 연결한 미리보기입니다. 실제 자전거 도로 경로가 아니므로 주행 전 도로 상황을 확인하세요.</p>
  <label>코스 이름</label><input value={courseName} onChange={e=>setCourseName(e.target.value)} placeholder="예: 한강 저녁 코스"/><div className="courseEditActions"><button onClick={undoCoursePoint} disabled={!start}><RotateCcw/>한 단계 취소</button><button onClick={resetCourse} disabled={!start}>전체 초기화</button></div><button className="primaryButton full" onClick={saveCourse}><Save/>코스 저장</button>{courseId&&<button className="rideCourseButton" onClick={()=>setTab("ride")}><Play/>저장한 코스로 주행하기</button>}</div>
  <h3>저장한 코스 <small>{courses.length}</small></h3><div className="savedList">{courses.length?courses.map(c=><div className="savedItem" key={c.id}><button onClick={()=>{setCourseId(c.id);setStart(c.start);setEnd(c.end);setWaypoints(c.waypoints||[]);setPreference(c.preference||"bike")}}>{c.name}<span>경유지 {c.waypoints?.length||0}개 · {c.preference==="road"?"일반도로":c.preference==="shared"?"공용도로":"자전거도로"} 우선</span></button><button className="iconButton" onClick={()=>deleteCourse(c.id)}><Trash2/></button></div>):<Empty text="아직 저장한 코스가 없습니다."/>}</div></aside>
  <section className="mapCard compact"><div className="mapWrap"><div ref={courseEl} className="map"/><MapSetup/></div><div className="mapFooter">버튼으로 지점 종류를 고른 뒤 지도나 검색 결과를 누르세요.</div></section></div>
 </TabsContent>
 <TabsContent value="ride" className={riding?"ridingView":""}><PageTitle eyebrow="RIDE NAVIGATION" title="주행 내비게이션" text="코스를 따라 달리거나 현재 위치에서 바로 자유 주행을 기록하세요. 실제 도로 상황과 교통법규를 우선하세요."/><div className="rideControls"><select value={courseId} onChange={e=>setCourseId(e.target.value)} disabled={riding}><option value="">코스 없이 자유 주행 가능</option>{courses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{!riding?<><button className="startButton" onClick={()=>beginRide(false)} disabled={!selectedCourse}><Play/>코스 주행</button><button className="freeRideButton" onClick={()=>beginRide(true)}><Navigation/>현재 위치 자유 주행</button></>:<><button className="pauseButton" onClick={togglePause}>{paused?<Play/>:<Pause/>}{paused?"계속":"일시정지"}</button><button className="stopButton" onClick={stopRide}><CircleStop/>주행 종료·저장</button></>}{selectedCourse&&!riding&&<a className="kakaoLink" href={`https://map.kakao.com/link/to/${encodeURIComponent(selectedCourse.name)},${selectedCourse.end.lat},${selectedCourse.end.lng}`} target="_blank" rel="noreferrer">카카오맵 길안내 ↗</a>}</div>{riding&&<div className="recordingWarning"><strong>● {freeRiding?"자유 주행":"코스 주행"} 기록 중</strong><span>브라우저를 닫거나 앱을 강제 종료하면 GPS 기록이 중단될 수 있습니다.</span></div>}<div className="rideStats"><RideStat label="주행 시간" value={fmtTime(elapsed)}/><RideStat label="주행 거리" value={fmtDistance(rideDistance)}/><RideStat label="평균 속도" value={`${avgSpeed.toFixed(1)} km/h`}/><RideStat label="GPS 정확도" value={gpsAccuracy==null?"--":`±${gpsAccuracy} m`}/></div><p className={`notice ${riding?"active":""}`}>{paused?"일시정지 중 · 안전한 곳에서 계속 버튼을 누르세요.":notice}</p><section className="mapCard compact"><div className="mapWrap"><div ref={rideEl} className="map"/><MapSetup/></div></section></TabsContent>
 <TabsContent value="records"><PageTitle eyebrow="RIDE HISTORY" title="나의 주행 기록" text="Strava와 앱에서 기록한 라이딩을 최대 100개까지 한곳에서 확인합니다."/><RecordsDashboard rides={rides} strava={strava} yearlyStrava={yearlyStrava} connected={stravaConnected} syncing={syncing} message={recordMessage} lastSynced={lastSynced} yearComplete={yearComplete} calendarDate={calendarDate} setCalendarDate={setCalendarDate} sync={()=>syncStrava()} upload={uploadRide} remove={deleteRide}/><div className="hiddenMap"><div ref={recordEl}/></div></TabsContent>
 </Tabs></section></main>
}

function PageTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="pageTitle"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>}
function Stat({label,value,note}:{label:string;value:string;note:string}){return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function RideStat({label,value}:{label:string;value:string}){return <article><span>{label}</span><strong>{value}</strong></article>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
function MapCard({title,message,mapRef,setup,action}:{title:string;message:string;mapRef:React.RefObject<HTMLDivElement|null>;setup:React.ReactNode;action:React.ReactNode}){return <section className="mapCard"><div className="mapHeader"><div><p className="eyebrow">LIVE MAP</p><h2>{title}</h2><p>{message}</p></div>{action}</div><div className="mapWrap"><div ref={mapRef} className="map"/>{setup}</div></section>}

type Unified={id:string;name:string;date:Date;distance:number;moving:number;average:number;elevation:number;polyline?:string;points?:Point[];source:"strava"|"app";ride?:Ride};
function RecordsDashboard({rides,strava,yearlyStrava,connected,syncing,message,lastSynced,yearComplete,calendarDate,setCalendarDate,sync,upload,remove}:{rides:Ride[];strava:StravaActivity[];yearlyStrava:StravaActivity[];connected:boolean;syncing:boolean;message:string;lastSynced:string;yearComplete:boolean;calendarDate:Date;setCalendarDate:(d:Date)=>void;sync:()=>void;upload:(r:Ride)=>void;remove:(id:string)=>void}){
 const [visibleCount,setVisibleCount]=useState(20),[selectedDay,setSelectedDay]=useState<number|null>(null);
 const convert=(a:StravaActivity):Unified=>({id:`s-${a.id}`,name:a.name,date:new Date(a.start_date_local),distance:a.distance,moving:a.moving_time*1000,average:a.average_speed*3.6,elevation:a.total_elevation_gain||0,polyline:a.map?.summary_polyline,source:"strava"});
 const stravaIds=new Set([...strava,...yearlyStrava].map(a=>a.id)),externalIds=new Set([...strava,...yearlyStrava].map(a=>a.external_id).filter(Boolean));
 const isSynced=(r:Ride)=>Boolean((r.stravaActivityId&&stravaIds.has(r.stravaActivityId))||externalIds.has(`riding-assistant-${r.id}`));
 const apps:Unified[]=rides.filter(r=>!isSynced(r)).map(r=>({id:`a-${r.id}`,name:r.courseName,date:new Date(r.startedAt),distance:r.distance,moving:r.endedAt-r.startedAt,average:r.distance/Math.max(1,(r.endedAt-r.startedAt)/1000)*3.6,elevation:r.elevation||0,points:r.points,source:"app",ride:r}));
 const items:Unified[]=[...strava.map(convert),...apps].sort((a,b)=>b.date.getTime()-a.date.getTime()).slice(0,100),yearItems:Unified[]=[...(yearlyStrava.length?yearlyStrava:strava).map(convert),...apps];
 const now=new Date(),weekStart=new Date(now);weekStart.setDate(now.getDate()-((now.getDay()+6)%7));weekStart.setHours(0,0,0,0);const monthStart=new Date(now.getFullYear(),now.getMonth(),1),yearStart=new Date(now.getFullYear(),0,1);
 const sum=(from:Date)=>{const x=yearItems.filter(i=>i.date>=from&&i.date<=now);return{km:x.reduce((s,i)=>s+i.distance,0)/1000,count:x.length}};
 const week=sum(weekStart),month=sum(monthStart),year=sum(yearStart),first=new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1),last=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,0),offset=(first.getDay()+6)%7,days=Array.from({length:offset+last.getDate()},(_,i)=>i<offset?null:i-offset+1),dayItems=selectedDay?yearItems.filter(x=>x.date.getFullYear()===calendarDate.getFullYear()&&x.date.getMonth()===calendarDate.getMonth()&&x.date.getDate()===selectedDay):[],dayKm=dayItems.reduce((s,x)=>s+x.distance,0)/1000;
 const ActivityCard=({i}:{i:Unified})=><article className="activityCard"><RouteThumb polyline={i.polyline} points={i.points}/><div className="activityInfo"><span>{i.source==="strava"?"STRAVA":"이 앱"} · {i.date.toLocaleString("ko-KR",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"})}</span><strong>{i.name}</strong><div className="activityMetrics"><Metric label="거리" value={fmtDistance(i.distance)}/><Metric label="이동시간" value={fmtTime(i.moving)}/><Metric label="평균속도" value={`${i.average.toFixed(1)} km/h`}/><Metric label="획득고도" value={`${Math.round(i.elevation)} m`}/></div></div>{i.ride&&<div className="activityActions"><button onClick={()=>upload(i.ride!)} disabled={i.ride.uploaded||Boolean(i.ride.uploadId)}><UploadCloud/>{i.ride.uploaded?"업로드됨":i.ride.uploadId?"처리 중":"Strava 업로드"}</button><button onClick={()=>remove(i.ride!.id)} aria-label={`${i.name} 기록 삭제`}><Trash2/></button></div>}</article>;
 return <><div className="recordToolbar"><div>{connected?<span className="stravaConnected">● Strava 연결됨</span>:<a className="stravaButton" href="/api/strava/auth">STRAVA 연결하기</a>}<button className="syncButton" onClick={sync} disabled={syncing}><RefreshCw/>{syncing?"동기화 중":"기록 동기화"}</button></div><span>{message||lastSynced&&`마지막 동기화 ${new Date(lastSynced).toLocaleString("ko-KR",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}`}</span></div>{!yearComplete&&<p className="notice">연간 기록을 모두 확인하지 못해 현재 합계는 일부 기록 기준입니다.</p>}<div className="achievementGrid"><Achievement label="이번 주" {...week}/><Achievement label="이번 달" {...month}/><Achievement label={`${now.getFullYear()}년 1월 1일부터${yearComplete?"":" (일부)"}`} {...year}/></div><div className="historyGrid"><section className="calendarCard"><div className="calendarHeader"><button onClick={()=>{setSelectedDay(null);setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1))}} aria-label="이전 달">‹</button><strong>{calendarDate.getFullYear()}년 {calendarDate.getMonth()+1}월</strong><button onClick={()=>{setSelectedDay(null);setCalendarDate(new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1))}} aria-label="다음 달">›</button></div><div className="weekdays">{["월","화","수","목","금","토","일"].map(x=><span key={x}>{x}</span>)}</div><div className="calendarDays">{days.map((d,i)=>{const count=d?yearItems.filter(x=>x.date.getFullYear()===calendarDate.getFullYear()&&x.date.getMonth()===calendarDate.getMonth()&&x.date.getDate()===d).length:0;return <button key={i} disabled={!d} onClick={()=>d&&setSelectedDay(d)} className={`${count?"rode":""} ${selectedDay===d?"selected":""}`}>{d&&<><span>{d}</span>{count>0&&<><Bike/><small>{count}</small></>}</>}</button>})}</div>{selectedDay&&<div className="daySummary"><strong>{calendarDate.getMonth()+1}월 {selectedDay}일</strong><span>{dayItems.length}회 · {dayKm.toFixed(1)} km</span>{dayItems.map(x=><small key={x.id}>{x.name} · {fmtDistance(x.distance)}</small>)}</div>}</section><section className="activityList">{items.length?<>{items.slice(0,visibleCount).map(i=><ActivityCard key={i.id} i={i}/>)}{visibleCount<items.length&&<button className="loadMore" onClick={()=>setVisibleCount(v=>Math.min(items.length,v+20))}>기록 20개 더 보기</button>}</>:<Empty text="Strava를 연결하거나 앱에서 주행을 기록해 주세요."/>}</section></div></>;
}
function Achievement({label,km,count}:{label:string;km:number;count:number}){return <article><span>{label}</span><strong>{km.toFixed(1)}<small> km</small></strong><b>{count}회 라이딩</b></article>}
function Metric({label,value}:{label:string;value:string}){return <div><span>{label}</span><b>{value}</b></div>}
function RouteThumb({polyline,points}:{polyline?:string;points?:Point[]}){const el=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false),pts=points?.length?points:(polyline?decodePolyline(polyline):[]);useEffect(()=>{const node=el.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting){setVisible(true);observer.disconnect()}},{rootMargin:"180px"});observer.observe(node);return()=>observer.disconnect()},[]);useEffect(()=>{if(!visible||pts.length<2)return;let tries=0;const timer=setInterval(()=>{tries++;if(!window.kakao||!el.current){if(tries>40)clearInterval(timer);return}clearInterval(timer);const bounds=new window.kakao.maps.LatLngBounds(),path=pts.filter((_,i)=>i%Math.max(1,Math.floor(pts.length/300))===0).map(p=>{const x=new window.kakao!.maps.LatLng(p.lat,p.lng);bounds.extend(x);return x}),map=new window.kakao.maps.Map(el.current,{center:path[0],level:7}),line=new window.kakao.maps.Polyline({path,strokeWeight:5,strokeColor:"#176b4a",strokeOpacity:.95});line.setMap(map);map.setBounds(bounds)},250);return()=>clearInterval(timer)},[polyline,visible]);return <div ref={el} className="routeThumb">{(!visible||pts.length<2)&&<span className="thumbPlaceholder"><Bike/>{pts.length<2?"경로 없음":"지도 준비"}</span>}</div>}
function decodePolyline(s:string){const p:Point[]=[];let i=0,lat=0,lng=0;while(i<s.length){let b=0,shift=0,result=0;do{b=s.charCodeAt(i++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lat+=(result&1)?~(result>>1):result>>1;shift=0;result=0;do{b=s.charCodeAt(i++)-63;result|=(b&31)<<shift;shift+=5}while(b>=32);lng+=(result&1)?~(result>>1):result>>1;p.push({lat:lat/1e5,lng:lng/1e5})}return p}
